#数据库配置信息
dbIp: localhost
dbPort: 3306
dbName: ltsok
dbUser: root
dbPwd: root

#服务port
serverPort: 9999
server:
  port: ${serverPort}
#  servlet:
#    context-path: /ltsok

#mybatis配置
mybatis:
  type-aliases-package: com.lts.course.entity
  mapper-locations: classpath*:mapper/*.xml

#datasource配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${dbIp}:${dbPort}/${dbName}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: ${dbUser}
    password: ${dbPwd}
